AXIS_COUNT = 8
BUTTON_COUNT = 24
CHANNEL_COUNT = AXIS_COUNT + BUTTON_COUNT

AXIS_ROLL = 0
AXIS_PITCH = 1
AXIS_THROTTLE = 2
AXIS_YAW = 3
AXIS_ARM = 4
AXIS_MODE = 5
AXIS_DIAL_S1 = 6
AXIS_DIAL_S2 = 7

FIRST_SPARE_BUTTON = 14
RESET_BUTTON = 14
RESET_CHANNEL = AXIS_COUNT + RESET_BUTTON

IMAGE_HEIGHT = 64
IMAGE_WIDTH = 128
RATE_HZ = 50
STEP_SECONDS = 1.0 / RATE_HZ
